### PR TITLE
Please review this Issue #764

### PR DESCRIPTION
**Pull request by erikweibust**
I hope this works. I'm hoping my commit turns in to a Pull Request to close CodingTrain Rainbow-Poem #764

### CODE REVIEW

**Comment by erikweibust** [comment]
I think this is on my fork; not on CodingTrain's.

**Comment by akraus53** [comment]
that's perfectly fine! if you can reopen it, I'll merge it!

**Comment by erikweibust** [comment]
I don't think I know how to unclose this? I'm afraid I need to go back and watch the videos. :(

**Comment by akraus53** [comment]
I'm so sorry :D this looked right. but it was wrong! if you create a pull request, make sure you compare against the correct branch *by the Coding Train*, not your own branch

**Pull request closed without merging**
